import { Inter } from "next/font/google";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

export const metadata = {
  title: "Wealth Wise",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }) {
  return (<html lang="en">
    <head>
      <ColorSchemeScript  defaultColorScheme="dark"/>
    </head>
    <body >
      <MantineProvider  defaultColorScheme="dark">{children}</MantineProvider>
    </body>
  </html>);
}


